# Generated by Django 4.0.2 on 2022-02-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='author',
            new_name='teacher',
        ),
    ]
