# Generated by Django 4.0.2 on 2022-02-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_author_classroom_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='code',
            field=models.CharField(max_length=16),
        ),
    ]
