# Generated by Django 4.0.2 on 2022-02-19 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_assignment_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='due_date',
            new_name='due_date_time',
        ),
    ]
