# Generated by Django 4.0.2 on 2022-02-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_submission_text_submission_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='points',
            field=models.PositiveSmallIntegerField(default=10),
            preserve_default=False,
        ),
    ]
