# Generated by Django 4.0.2 on 2022-02-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_assignment_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='points',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
