# Generated by Django 4.0.2 on 2022-04-28 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_comment_announcement_remove_comment_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='student',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
