# Generated by Django 4.0.2 on 2022-04-29 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_alter_assignment_classroom'),
        ('announcement', '0002_alter_announcement_classroom'),
        ('api', '0020_remove_submission_assignment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classroom',
        ),
    ]
